[package]
name = "restaurant"
version = "0.1.0"
authors = ["yangyunfeng666 <445482919@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
